module.exports = {
  acl: require("./acl"),
  auth: require("./auth"),
  database: require("./database"),
  environment: require("./environment"),
  events: require("./events"),
  facebook: require("./facebook"),
  general: require("./general"),
  google: require("./google"),
  ical: require("./ical"),
  keys: require("./keys"),
  photos: require("./photos"),
  server: require("./server"),
  storage: require("./storage"),
  uploads: require("./uploads"),
};
