name: Deploy to PRODUCTION environment

on:
  push:
    branches:
      - master
    paths:
      - web/**
      - ".github/workflows/deploy-production.yml"

jobs:
  build-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the updated source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push it to the docker.bosan.cz repository
        uses: docker/build-push-action@v4
        with:
          build-args: NG_CONFIGURATION=production
          push: true
          context: .
          tags: "ghcr.io/bosancz/web:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
