name: Deploy web

on:
  push:
    branches:
      - master
    paths:
      - web/**
      - ".github/workflows/deploy-web.yml"
      - ".github/workflows/build-docker.yml"

jobs:
  build-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "./web"
          push: true
          tags: bosancz/web:latest
