name: Test client (master)

on:
  pull_request:
    branches:
      - master
    paths:
      - client/**
      - '.github/workflows/master-test-client.yml'

jobs:
  build-docker:
    name: Docker Image
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@master
      - name: Build the Docker image
        run: docker build ./client --tag bosancz/bosan.cz-client