name: Test server (master)

on:
  pull_request:
    branches:
      - master
    paths:
      - server/**
      - '.github/workflows/master-test-server.yml'

jobs:
  build-docker:
    name: Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@master
      - name: Build the Docker image
        run: docker build ./server --tag bosancz/bosan.cz-server