name: Build server (prod)

on:
  push:
    branches:
      - prod
    paths:
      - server/**
      - '.github/workflows/master-build-server.yml'

jobs:
  build-docker:
    name: Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@master
      - name: Build the Docker image
        run: docker build ./server --tag bosancz/bosan.cz-server:prod
      - name: Login to DockerHub
        run: docker login --username=${{secrets.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}}
      - name: Push to DockerHub
        run: docker push bosancz/bosan.cz-server:prod